#!/bin/zsh
# vim: set foldlevel=0 foldmethod=marker:

#  antigen {{{
source /usr/local/share/antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundle https://github.com/technomancy/leiningen zsh_completion.zsh

#bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle ruby
antigen bundle rails
antigen bundle gem
antigen bundle tmuxinator

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

antigen apply
# }}}

# Source the prompt {{{
#-------------------------------------------------------------------------------
if [[ ! -n "$ZSHRUN" ]]; then
    source $HOME/dotfiles/zsh/zsh_prompt
fi
# Precmd functions local array variable <<2
#-------------------------------------------------------------------------------
local -a precmd_functions
# >>2
# Precmd functions <<2
#------------------------------------------------------------------------------
# Run precmd functions so we get our pimped out prompt
#------------------------------------------------------------------------------
precmd_functions=( precmd_prompt )
# >>2
# }}}

# General Settings {{{
# Autoload tab completion {{{
#-------------------------------------------------------------------------------
autoload -U compinit
compinit -C
# }}}
# Modify default zsh directory coloring on ls commands {{{
#-------------------------------------------------------------------------------
export LSCOLORS=gxfxcxdxbxegedabagacad
# }}}
# Completion settings {{{
#-------------------------------------------------------------------------------
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' list-colors "$LS_COLORS"
zstyle -e ':completion:*:(ssh|scp|sshfs|ping|telnet|nc|rsync):*' hosts '
    reply=( ${=${${(M)${(f)"$(<~/.ssh/config)"}:#Host*}#Host }:#*\**} )'
# }}}
# Set the desired setup options man zshoptions {{{
#-------------------------------------------------------------------------------
# If command can't be executed, and command is name of a directory, cd to directory
setopt  auto_cd
# Make cd push the old directory onto the directory stack.
setopt  auto_pushd
# Safety for overwriting files use >| instead of > to over write files
setopt  noclobber
# Prevents aliases on the command line from being internally substituted before
# completion is attempted. The effect is to make the alias a distinct command
# for completion purposes.
setopt  complete_aliases
# Treat the #, ~ and ^ characters as part of patterns for filename
# generation, etc.  (An initial unquoted `~' always produces named directory
# expansion.)
setopt  extended_glob
# If a new command line being added to the history list duplicates an older one,
# the older command is removed from the list (even if it is not the previous event).
setopt  hist_ignore_all_dups
#  Remove command lines from the history list when the first character on the line
#  is a space, or when one of the expanded aliases contains a leading space.
setopt  hist_ignore_space
# This  option  both  imports new commands from the history file, and also
# causes your typed commands to be appended to the history file
setopt  share_history
setopt  noflowcontrol
# When listing files that are possible completions, show the type of each file
# with a trailing identifying mark.
setopt  list_types
# Append a trailing / to all directory names resulting from filename
# generation (globbing).
setopt  mark_dirs
# Perform a path search even on command names with slashes in them.
# Thus if /usr/local/bin is in the user's path, and he or she types
# X11/xinit, the  command /usr/local/bin/X11/xinit will be executed
# (assuming it exists).
setopt  path_dirs
# If set, `%' is treated specially in prompt expansion.
setopt  prompt_percent
# If set, parameter expansion, command substitution and arithmetic
# expansion are performed in prompts.
# Substitutions within prompts do not affect the command status.
setopt  prompt_subst
# }}}
# History settings {{{
#-------------------------------------------------------------------------------
HISTFILE=$HOME/.zsh_history
HISTFILESIZE=65536  # search this with `grep | sort -u`
HISTSIZE=4096
SAVEHIST=4096
REPORTTIME=60       # Report time statistics for progs that take more than a minute to run
# }}}
# utf-8 in the terminal, will break stuff if your term isn't utf aware {{{
#-------------------------------------------------------------------------------
export LANG=en_US.UTF-8
export LC_ALL=$LANG
export LC_COLLATE=C
# }}}
# Set grepoptions {{{
#-------------------------------------------------------------------------------
export GREP_OPTIONS='--color=auto'
# }}}
# Use the correct ctags {{{
#-------------------------------------------------------------------------------
# PATH="/usr/local/cloudera/bin:/usr/local/cloudera-hive/bin:/usr/local/sbin:/usr/local/bin:$PATH"
# PATH="/usr/local/cloudera/bin:/usr/local/cloudera-hive/bin:/usr/local/sbin:/usr/local/bin:$PATH"
# }}}
# Editor and display configurations {{{
#-------------------------------------------------------------------------------
export EDITOR='nvim'
export VISUAL='nvim'
export GIT_EDITOR=$EDITOR
export LESS='-imJMWR'
export PAGER="less $LESS"
export MANPAGER=$PAGER
export GIT_PAGER=$PAGER
# }}}
# Specify virtualenv directory {{{
export WORKON_HOME=$HOME/.virtualenvs
# }}}
# Eliminate lag between transition from normal/insert mode {{{
#-------------------------------------------------------------------------------
# If this causes issue with other shell commands it can be raised default is 4
export KEYTIMEOUT=1
# }}}
# }}}

# if [ -n "$VIRTUAL_ENV" ]; then
#   ."$VIRTUAL_ENV/bin/activate"
# fi

# Aliases {{{
alias rm="rm -i"
alias l="ls -CF"
alias less="less -S"
alias vim="nvim"
alias chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"
alias hstart="/usr/local/cloudera/sbin/start-dfs.sh;/usr/local/cloudera/sbin/start-yarn.sh"
alias hstop="/usr/local/cloudera/sbin/stop-yarn.sh;/usr/local/cloudera/sbin/stop-dfs.sh"
# }}}

# Functions {{{
# Workon virtualenv {{{
# [[ -a /usr/local/bin/virtualenvwrapper.sh ]] && source /usr/local/bin/virtualenvwrapper.sh
#
# workon_virtualenv() {
#   if [[ -d .git ]]; then
#     VENV_CUR_DIR="${PWD##*/}"
#     if [[ -a ~/.virtualenvs/$VENV_CUR_DIR ]]; then
#       deactivate > /dev/null 2>&1
#       source ~/.virtualenvs/$VENV_CUR_DIR/bin/activate
#     fi
#   fi
# }
# }}}
# Run virtual environment functions on cd {{{
# cd() {
#   builtin cd "$@"
#   workon_virtualenv
# }
# }}}
# }}}

# /usr/local/opt/erlang/lib/erlang/man
#
autoload -U edit-command-line
zle -N edit-command-line
bindkey -M vicmd v edit-command-line

if [ -f ~/.env ]; then
  source ~/.env
fi

# rbenv {{{
eval "$(rbenv init -)"
# }}}

#export http_proxy=http://localhost:3128
#export https_proxy=http://localhost:3128
#export HTTP_PROXY=http://localhost:3128
#export HTTPS_PROXY=http://localhost:3128
#export NO_PROXY=localhost,127.0.0.1,0.0.0.0
#export no_proxy=localhost,127.0.0.1,0.0.0.0
export GOPATH=$HOME/go

wlssh () {
  clientid="$1"
  clientenv="$2"
  ip="${@:3}"
  if [[ -z $clientid || -z $clientenv || -z $ip ]]
  then
          echo 'usage: wlssh <clientid> <envname> <ip>'
          return
  fi
  ssh-add -D
  ssh-add -K ~/.ssh/id_rsa
  ssh-add ~/.ssh/$1-$2-provisioning.pem
  ssh -AJ vpn_$clientid\_$clientenv ubuntu@$ip
}

wlcssh () {
  clientid="$1"
  clientenv="$2"
  ips="${@:3}"
  if [[ -z $clientid || -z $clientenv || -z $ips ]]
  then
          echo 'usage: wlcssh <clientid> <envname> <ips>'
          return
  fi
  ssh-add -D
  ssh-add -K ~/.ssh/id_rsa
  ssh-add ~/.ssh/$clientid-$clientenv-provisioning.pem
  eval "csshX -l ubuntu --ssh_args \"-J openvpnas@vpn.$clientenv.$clientid.weblinc.com -o StrictHostKeyChecking=no\" $ips"
}

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
